### ISSUE TITLE
想问一下~这个用的d2admin 是哪个版本

### ISSUE THREAD

**Issue by obrua** [huguodong/d2admin-permission#1]
我比对了下 改了很多。。。应该是比对的版本不对~作者还记得当初用的是d2admin 哪个提交版本吗

感谢

**Comment by huguodong** [comment]
0.0.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huguodong/d2admin-permission"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 中午1:41
收件人:&nbsp;"huguodong/d2admin-permission"<d2admin-permission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huguodong/d2admin-permission] 想问一下~这个用的d2admin 是哪个版本 (#1)





 
我比对了下 改了很多。。。应该是比对的版本不对~作者还记得当初用的是d2admin 哪个提交版本吗
 
感谢
